# Generated by Django 3.1 on 2019-10-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_quadrinhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=500)),
                ('serie', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=60)),
                ('senha', models.CharField(max_length=80)),
            ],
        ),
    ]
